# Different language support
language: en-us

# Minimum characters/number limit allowed
min:
  age: 0
  first-name: 3
  middle-name: 3
  last-name: 3

# Maximum characters/number limit allowed
max:
  age: 100
  first-name: 12
  middle-name: 10
  last-name: 16

view-format:
  - ""
  - "         &a<player-name>'s Info         "
  - " &f&o<desc>"
  - " &7Title: &f<title>"
  - " &7First: &f<first>"
  - " &7Middle: &f<middle>"
  - " &7Last: &f<last>"
  - " &7Age: &f<age>"
  - " &7Gender: &f<gender>"
  - ""